src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("feedback.urls")),
]

src/core/urls.py
from django.urls import path

from core.views import healthcheck

app_name = "core"

urlpatterns = [
    path("healthcheck/", healthcheck),
]

src/django_celery/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("feedback.urls")),
]

src/feedback/urls.py
from django.urls import path

from feedback.views import FeedbackFormView, SuccessView

app_name = "feedback"

urlpatterns = [
    path("", FeedbackFormView.as_view(), name="feedback"),
    path("success/", SuccessView.as_view(), name="success"),
]

src/feedback/forms.py
from time import sleep

from django import forms

from mail.models import Letter


class FeedbackForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    email = forms.EmailField(label="Email Address")
    message = forms.CharField(
        label="Message", widget=forms.Textarea(attrs={"rows": 5})
    )

    def send_email(self):
        message = self.cleaned_data["message"]
        Letter.objects.create(
            subject="Your Feedback",
            message=f"\t{message}\n\nThank you!",
            from_email="support@example.com",
            recipient=self.cleaned_data["email"],
        )

src/core/views.py
from django.http import HttpResponse

from django.db.migrations.executor import MigrationExecutor
from django.db import connections, DEFAULT_DB_ALIAS


def is_database_synchronized(database: str):
    connection = connections[database]
    connection.prepare_database()
    executor = MigrationExecutor(connection)
    targets = executor.loader.graph.leaf_nodes()
    return not executor.migration_plan(targets)


def healthcheck(request):
    if is_database_synchronized(DEFAULT_DB_ALIAS):
        return HttpResponse('OK')
    else:
        return HttpResponse('NOK', status=400)

src/feedback/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from feedback.forms import FeedbackForm


class FeedbackFormView(FormView):
    template_name = "feedback/feedback.html"
    form_class = FeedbackForm
    success_url = "/success/"

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class SuccessView(TemplateView):
    template_name = "feedback/success.html"

src/feedback/templates/feedback/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Feedback</title>
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

src/feedback/templates/feedback/feedback.html
{% extends 'feedback/base.html' %}

{% block content %}

    <h1>Feedback form</h1>
    
    <p>Please send us your feedback.</p>

    {% if form.errors %}
        <ul class="errors">
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <label>{{ field.label }}</label>
            {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Send</button>
    </form>

{% endblock content %}

src/feedback/templates/feedback/success.html
{% extends 'feedback/base.html' %}

{% block content %}

<h1>Thank You!</h1>

<p>Your review has been sent.</p>
<p>If there is a desire, we are ready to <a href="{% url 'feedback:feedback' %}">listen more</a>.</p>

{% endblock content %}